#ifndef __ENC28J60_DEFINES_H
#define __ENC28J60_DEFINES_H

#include "stm32f4xx.h"

#define ETHERNET_LED_GPIO GPIOA
#define ETHERNET_LED_PIN GPIO_PIN_8
#define ETHERNET_CS_GPIO GPIOA
#define ETHERNET_CS_PIN GPIO_PIN_9
#define ETHERNET_CS_DELAY 10

#endif /* __ENC28J60_DEFINES_H */
